_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
batch_size:
    value: 1112
epochs:
    value: 100
h_dim:
    value: 32
in_channels:
    value: 5
l_b:
    value: 0.96
l_e:
    value: 10
lr:
    value: 0.01
momentum:
    value: 0.9
optimizer:
    value: adam
p_shuffle:
    value: 0.3
size_per_class:
    value: 500
temperature:
    value: 0.3
weight_decay:
    value: 0.0001
