method: bayes

metric:
  name: best_ari
  goal: maximize

parameters:
  epochs:
    value: 100
  momentum:
    value: 0.9
  weight_decay:
    value: 0.0001
  size_per_class:
    value: 500
  l_e:
    value: 10   # max epoch for linear warm-up of lambda
  l_b:
    value: 0.96 # base for exponential decay of lambda
  in_channels:
    value: 5
  lr:
    values: [0.01]
    # distribution: uniform
    # min: 0.0001
    # max: 0.05
  batch_size:
    value: 1112
  p_shuffle:
    values: [0.1, 0.3, 0.5, 0.7, 0.9]
  h_dim:
    value: 32 # [32, 64, 128, 256]
  projection_dim:
    value: 32 # [32, 64, 128, 256]
  temperature:
    value: 0.3
    # distribution: uniform
    # min: 0.07
    # max: 0.5
  scheduler:
    values: [Cyclic, LambdaLR]
  optimizer:
    value: adam